import {chromium} from 'playwright';import AxeBuilder from '@axe-core/playwright';import fs from 'node:fs';import assert from 'node:assert/strict';import {marked} from 'marked';
const base='http://127.0.0.1:4173/schrodingers_civ/';
const browser=await chromium.launch();const context=await browser.newContext({viewport:{width:360,height:800},hasTouch:true});const page=await context.newPage();
const freshReport={browser:browser.version(),platform:process.platform,routes:[],layouts:[],interactions:[],consoleErrors:[],networkFailures:[],axe:[],limitations:['Chromium emulation, not physical devices.','200% layout tested via CSS zoom and a halved effective viewport; browser-native desktop zoom and OS text scaling are not automated.','No live server configuration was inspected.']};
const interactionsOnly=process.argv.includes('--interactions-only');const report=interactionsOnly?JSON.parse(fs.readFileSync('qa/browser-report.json')):freshReport;
page.on('pageerror',e=>report.consoleErrors.push(e.message));page.on('requestfailed',r=>report.networkFailures.push({url:r.url(),failure:r.failure()}));
fs.mkdirSync('qa/screenshots',{recursive:true});
const routes=JSON.parse(fs.readFileSync('dist/routes.json'));const chapters=JSON.parse(fs.readFileSync('src/content/chapters.json'));const story=fs.readFileSync('src/content/tale-source.md','utf8');const starts=[...story.matchAll(/^#{1,3} (?:PROLOGUE:|[IVX]+\. |EPILOGUE:).*$/gm)];
async function layout(label){const metrics=await page.evaluate(()=>({width:innerWidth,height:innerHeight,scrollWidth:document.documentElement.scrollWidth,overflow:document.documentElement.scrollWidth>innerWidth+1,brokenImages:[...document.images].filter(i=>!i.complete||!i.naturalWidth).map(i=>i.src),bodyFont:getComputedStyle(document.querySelector('.story-prose')||document.body).fontSize}));report.layouts.push({label,...metrics});if(metrics.overflow)console.log(await page.evaluate(()=>[...document.querySelectorAll('main *')].filter(e=>e.getBoundingClientRect().right>innerWidth+1).slice(0,10).map(e=>({tag:e.tagName,cls:e.className,right:e.getBoundingClientRect().right,text:e.textContent.slice(0,70)}))));assert(!metrics.overflow,label+' horizontal overflow');assert(!metrics.brokenImages.length,label+' broken image');}
for(const r of (interactionsOnly?[]:routes)){const response=await page.goto(base+r.route);await page.evaluate(async()=>{await Promise.all([...document.images].filter(i=>i.loading!=='lazy').map(i=>i.decode().catch(()=>{})));});assert.equal(response.status(),200);const reload=await page.reload();assert.equal(reload.status(),200);await page.evaluate(()=>Promise.all([...document.images].map(i=>{i.loading='eager';return i.decode().catch(()=>{});})));await layout(r.route+' phone');
 if(r.route.startsWith('tale/')&&r.route!=='tale/'){const ci=chapters.findIndex(c=>'tale/'+c.slug+'/'===r.route);const source=story.slice(starts[ci].index,starts[ci+1]?.index??story.length).trim().replace(/^.*\n/,'').replace(/\n---\s*$/,'').trim();const expected=await page.evaluate(html=>{const el=document.createElement('div');el.innerHTML=html;return el.innerHTML.trim();},marked.parse(source));const actual=await page.locator('.story-prose').innerHTML();assert.equal(actual.trim(),expected,`${r.route}: source prose changed`);await page.screenshot({path:`qa/screenshots/chapter-${String(ci+1).padStart(2,'0')}-phone.png`});const text=await page.locator('.story-prose').innerText();assert(text.length>400);}
 const results=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();report.axe.push({route:r.route,viewport:'360x800',violations:results.violations.map(v=>({id:v.id,impact:v.impact,help:v.help,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))}))});
 report.routes.push({route:r.route,status:response.status(),reload:reload.status()});fs.writeFileSync('qa/browser-report.json',JSON.stringify(report,null,2));console.log('Checked',r.route||'home');}
for(const [label,width,height] of (interactionsOnly?[]:[['phone-landscape',844,390],['tablet-portrait',768,1024],['tablet-landscape',1024,768],['desktop',1440,1000],['wide',1920,1080]])){await page.setViewportSize({width,height});for(const route of ['','audit/','atlas/','tale/the-song-of-head-office/']){await page.goto(base+route);await page.evaluate(()=>Promise.all([...document.images].map(i=>{i.loading='eager';return i.decode().catch(()=>{});})));await layout(route+' '+label);await page.screenshot({path:`qa/screenshots/${route.replaceAll('/','-')||'home-'}${label}.png`});}}
await page.setViewportSize({width:360,height:800});await page.goto(base+'atlas/');
const menu=page.locator('#navigation-dialog'),open=page.locator('.menu-button');
for(const method of ['escape','close','outside','selection']){await open.click();assert(await menu.evaluate(d=>d.open));assert(await menu.evaluate(d=>d.contains(document.activeElement)));await page.keyboard.press('Shift+Tab');assert(await menu.evaluate(d=>d.contains(document.activeElement)),'focus escaped modal');if(method==='escape')await page.keyboard.press('Escape');if(method==='close')await page.getByRole('button',{name:'Close menu',exact:true}).click();if(method==='outside')await page.mouse.click(8,200);if(method==='selection')await menu.getByRole('link',{name:'The full map',exact:true}).click();assert(!(await menu.evaluate(d=>d.open)));await page.waitForFunction(()=>document.activeElement?.classList.contains('menu-button'),{},{timeout:3000}).catch(async()=>{throw Error(method+' focus restoration: '+await page.evaluate(()=>document.activeElement.outerHTML.slice(0,200)));});report.interactions.push('Drawer '+method+' dismissal and focus restoration: pass');}
await open.click();const inertProof=await page.locator('#main').evaluate(el=>{el.focus();return document.activeElement!==el;});assert(inertProof,'modal background focusable');await page.keyboard.press('Escape');report.interactions.push('Native modal background inert: pass');
await page.locator('.viewer-window').focus();await page.keyboard.press('+');assert.equal(await page.locator('[data-scale]').textContent(),'150%');await page.keyboard.press('+');await page.keyboard.press('ArrowRight');assert(!(await page.locator('.viewer-window img').getAttribute('style')).includes('translate(0px, 0px)'));await page.keyboard.press('Home');assert.equal(await page.locator('[data-scale]').textContent(),'100%');
await page.getByRole('button',{name:'Zoom in',exact:true}).click();await page.locator('[data-pan]').click();assert.equal(await page.locator('.viewer-window').evaluate(el=>getComputedStyle(el).touchAction),'none');const bounds=await page.locator('.viewer-window').boundingBox();await page.mouse.move(bounds.x+180,bounds.y+150);await page.mouse.down();await page.mouse.move(bounds.x+230,bounds.y+200);await page.mouse.up();assert((await page.locator('.viewer-window img').getAttribute('style')).includes('translate(50px, 50px)'));await page.locator('[data-pan]').click();assert((await page.locator('.viewer-window').evaluate(el=>getComputedStyle(el).touchAction)).includes('pan-y'));await page.locator('[data-fit]').click();report.interactions.push('Viewer keyboard zoom, pan, Home reset, drag mode and ordinary scrolling mode: pass');
await page.goto(base+'tale/prologue/');await page.getByRole('button',{name:'View artwork'}).click();assert(await page.locator('.art-dialog').evaluate(d=>d.open));await page.keyboard.press('Escape');assert(await page.locator('.art-open').evaluate(b=>document.activeElement===b));await page.locator('a[rel=next]').click();assert(page.url().includes(chapters[1].slug));await page.goBack();assert(page.url().includes('/prologue/'));await page.goForward();assert(page.url().includes(chapters[1].slug));await page.keyboard.press('Alt+ArrowRight');await page.waitForURL('**/'+chapters[2].slug+'/');report.interactions.push('Artwork modal, next chapter, browser back/forward and Alt+ArrowRight: pass');
await page.emulateMedia({reducedMotion:'reduce'});assert(await page.evaluate(()=>matchMedia('(prefers-reduced-motion: reduce)').matches));report.interactions.push('Reduced-motion CSS active: pass');
await page.setViewportSize({width:1440,height:1000});await page.goto(base+'tale/the-song-of-head-office/');await page.evaluate(()=>document.documentElement.style.zoom='2');await page.screenshot({path:'qa/screenshots/tale-200-percent-css-zoom.png'});await layout('Tale at 200% CSS zoom');await page.evaluate(()=>document.documentElement.style.zoom='1');await page.setViewportSize({width:720,height:500});await layout('1440x1000 at 200% effective CSS viewport');
const missing=await page.goto(base+'not-a-real-route/');assert.equal(missing.status(),404);assert((await page.locator('h1').textContent()).includes('off the map'));report.interactions.push('Unknown route returns HTTP 404 with navigable page: pass');
const slash=await context.request.get(base+'atlas',{maxRedirects:0});assert.equal(slash.status(),308);report.interactions.push('Trailing slash redirect: 308');
const nojs=await browser.newContext({javaScriptEnabled:false,viewport:{width:360,height:800}});const np=await nojs.newPage();for(const route of ['audit/paper/','atlas/paper/','tale/prologue/']){await np.goto(base+route);await page.goto(base+route);const selector=route.startsWith('tale/')?'.story-prose':'.paper-prose';assert.equal((await np.locator(selector).innerText()).trim(),(await page.locator(selector).innerText()).trim(),route+' no-JS text differs');}await nojs.close();report.interactions.push('No-JavaScript complete reading: audit, Atlas and tale pass');
await page.goto(base);await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement.className),'skip');await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>document.activeElement.id),'main');report.interactions.push('Keyboard skip navigation: pass');
const perf=await page.evaluate(()=>({navigation:performance.getEntriesByType('navigation').map(n=>({domContentLoaded:n.domContentLoadedEventEnd,duration:n.duration,transferSize:n.transferSize})),resources:performance.getEntriesByType('resource').map(n=>({name:n.name,transferSize:n.transferSize,duration:n.duration}))}));report.localPerformance=perf;
fs.writeFileSync('qa/browser-report.json',JSON.stringify(report,null,2));await browser.close();const violations=report.axe.flatMap(x=>x.violations);console.log('Done:',report.routes.length,'routes,',report.layouts.length,'layout checks,',violations.length,'axe route violations');assert.equal(report.consoleErrors.length,0);assert.equal(report.networkFailures.length,0);assert.equal(violations.length,0,'Accessibility violations; see qa/browser-report.json');
