import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import crypto from 'node:crypto';
const base='/schrodingers_civ/',root=path.resolve('dist');
const walk=p=>fs.readdirSync(p,{withFileTypes:true}).flatMap(f=>f.isDirectory()?walk(path.join(p,f.name)):[path.join(p,f.name)]);
const all=walk(root),htmls=all.filter(p=>p.endsWith('.html'));let links=0,assets=0;
for(const p of htmls){const html=fs.readFileSync(p,'utf8');assert(!/\/Users\/|handoff\/|data:application\/pdf/.test(html),p+' leaked source or stale embedded PDF');assert.equal((html.match(/<h1(?: |>)/g)||[]).length,1,p+' must have exactly one page heading');assert(html.includes('rel="canonical" href="https://benamuwo.me/schrodingers_civ/'));
 for(const match of html.matchAll(/(?:href|src)="([^"]+)"/g)){const url=match[1];if(url.startsWith('http')||url.startsWith('mailto:'))continue;const [u,anchor]=url.split('#');let target=u?path.resolve(root,u.slice(base.length)):p;assert(!u||u.startsWith(base),`${p}: invalid base ${url}`);if(fs.existsSync(target)&&fs.statSync(target).isDirectory())target=path.join(target,'index.html');assert(fs.existsSync(target),`${p}: broken ${url}`);if(anchor&&target.endsWith('.html')){const t=fs.readFileSync(target,'utf8');assert(t.includes(`id="${anchor}"`),`${p}: missing anchor ${url}`);}links++;}
}
const manifests=JSON.parse(fs.readFileSync('dist/assets/source-manifest.json'));for(const a of manifests.assets){assert.equal(crypto.createHash('sha256').update(fs.readFileSync('dist/'+a.path)).digest('hex'),a.sha256);assets++;}
const chapters=JSON.parse(fs.readFileSync('src/content/chapters.json'));assert.equal(chapters.length,23);for(const c of chapters){assert(fs.existsSync(`dist/tale/${c.slug}/index.html`));assert(fs.existsSync('dist/assets/art/'+c.file));}
for(const f of ['audit.md','atlas.md','tale.md']){const s=fs.readFileSync('dist/assets/papers/'+f,'utf8');assert(s.includes('https://www.benamuwo.me/schrodingers_civ/'));assert(s.includes('https://github.com/RavenSeldon/schrodingers_civ'));for(const m of s.matchAll(/!\[[^\]]*\]\(([^)]+)\)/g))assert(fs.existsSync(path.resolve('dist/assets/papers',m[1])));}
const report={htmlDocuments:htmls.length,routes:JSON.parse(fs.readFileSync('dist/routes.json')).length,localLinksChecked:links,assetHashesChecked:assets,chapters:chapters.length,totalBytes:all.reduce((n,p)=>n+fs.statSync(p).size,0),checks:'All local links, fragment targets, base paths, image references, publication URLs, chapter assets, one-h1 structure and asset hashes passed.'};fs.mkdirSync('qa',{recursive:true});fs.writeFileSync('qa/static-check.json',JSON.stringify(report,null,2));console.log(report);
