import {chromium} from 'playwright';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';import AxeBuilder from '@axe-core/playwright';
const base='http://127.0.0.1:4173/schrodingers_civ/';const browser=await chromium.launch();const context=await browser.newContext({viewport:{width:360,height:800},hasTouch:true});const page=await context.newPage();const assets=JSON.parse(fs.readFileSync('dist/assets/source-manifest.json')).assets;const checks=[];
for(const a of assets){const res=await context.request.get(base+a.path);assert.equal(res.status(),200,a.path);assert.equal(crypto.createHash('sha256').update(await res.body()).digest('hex'),a.sha256,a.path+' HTTP content differs');checks.push({path:a.path,status:200,mime:res.headers()['content-type'],bytes:a.bytes});}
await page.goto(base+'atlas/');await page.getByRole('button',{name:'Zoom in',exact:true}).click();await page.getByRole('button',{name:'Pan mode',exact:true}).click();await page.locator('.viewer-window').scrollIntoViewIfNeeded();const box=await page.locator('.viewer-window').boundingBox();const cdp=await context.newCDPSession(page);const p1={x:box.x+100,y:box.y+130},p2={x:box.x+200,y:box.y+130};await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[p1,p2]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{...p1,x:p1.x-10}, {...p2,x:p2.x+10}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{...p1,x:p1.x-25}, {...p2,x:p2.x+25}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});const zoom=await page.locator('[data-scale]').textContent();assert(parseInt(zoom)>150,'touch pinch did not enlarge');await page.locator('[data-pan]').click();const before=await page.evaluate(()=>scrollY);await page.mouse.move(box.x+80,box.y+150);await page.mouse.wheel(0,160);await page.waitForTimeout(100);assert((await page.evaluate(()=>scrollY))>before,'viewer trapped ordinary wheel scrolling');
await page.goto(base+'audit/paper/');const downloadPromise=page.waitForEvent('download');await page.getByRole('link',{name:'Download PDF ↓',exact:true}).first().click();const download=await downloadPromise;assert.equal(download.suggestedFilename(),'audit.pdf');
// Contrast lower bounds assume pure-white artwork behind the opaque scrim.
const lum=rgb=>{const c=rgb.map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4;});return .2126*c[0]+.7152*c[1]+.0722*c[2];};const bg=[11,12,18].map(v=>v*.94+255*.06);const ratio=rgb=>(lum(rgb)+.05)/(lum(bg)+.05);const contrast={body:ratio([234,229,237]),emphasis:ratio([230,201,242]),worstCaseBackground:bg};assert(contrast.body>7&&contrast.emphasis>7);
await page.setViewportSize({width:1440,height:1000});const desktop=[];for(const route of ['','audit/','audit/paper/','atlas/','atlas/paper/','tale/prologue/']){await page.goto(base+route);const a=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();assert.equal(a.violations.length,0,route+' desktop axe violation');desktop.push({route,violations:0});}
await browser.close();fs.writeFileSync('qa/final-checks.json',JSON.stringify({httpAssets:checks,touchPinchScale:zoom,ordinaryWheelScroll:'passed',pdfDownload:'audit.pdf',storyContrast:contrast,desktopAxe:desktop},null,2));console.log('Verified',checks.length,'HTTP asset hashes and MIME responses; touch pinch',zoom,'; ordinary wheel scrolling, real PDF download, six desktop axe scans and worst-case story contrast pass.');
